"""iot table

Revision ID: 0cde8546be27
Revises: 
Create Date: 2019-06-26 11:08:16.567703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cde8546be27'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dht_22',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node', sa.String(length=10), nullable=True),
    sa.Column('temp', sa.String(length=7), nullable=True),
    sa.Column('hum', sa.String(length=7), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('m_q7',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node', sa.String(length=10), nullable=True),
    sa.Column('air', sa.String(length=6), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('m_q7')
    op.drop_table('dht_22')
    # ### end Alembic commands ###
